trigger:
  branches:
    exclude:
      - main
  paths:
    exclude:
      - CHANGELOG
      - '*.md'
      - '*.yaml'
      - '**/README'
      - '**/CHANGELOG'

parameters:
  - name: environment
    type: string
    default: tst
  - name: sourcePath
    type: string
    default: ./
  - name: serviceConnectionName
    type: string
  - name: resourceGroupName
    type: string
  - name: storageAccountName
    type: string
  - name: containerName
    type: string
  - name: terraformVersion
    type: string
    default: latest
  - name: clearCache
    type: boolean
    default: false

jobs:
  - job: UnitTestModule
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 0

      - task: TerraformInstaller@1
        displayName: 'Install Terraform'
        inputs:
          terraformVersion: '${{ parameters.terraformVersion }}'

      - bash: |
          set -e

          changed_files=$(git diff --name-only HEAD^ HEAD)

          changedModules=$(echo "$changed_files" \
            | grep -vE '\.yaml$|\.ps1$' \
            | cut -d'/' -f1 \
            | sort -u \
            | head -n 1)

          if [ -z "$changedModules" ]; then
            echo "##vso[task.logissue type=error]No module detected from changed files."
            exit 1
          fi

          echo "Detected changed module: $changedModules"
          echo "##vso[task.setvariable variable=changedModules]$changedModules"
        displayName: 'Detect Modified Module'

      - task: TerraformTaskV4@4
        displayName: 'Terraform Init for Module'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(changedModules)/unit'
          backendServiceArm: '${{ parameters.serviceConnectionName }}'
          backendAzureRmResourceGroupName: '${{ parameters.resourceGroupName }}'
          backendAzureRmStorageAccountName: '${{ parameters.storageAccountName }}'
          backendAzureRmContainerName: '${{ parameters.containerName }}'
          backendAzureRmKey: '$(changedModules)/${{ parameters.environment }}.tfstate'

      - task: TerraformTaskV4@4
        displayName: 'Terraform Test for Module'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'test'
          workingDirectory: '$(changedModules)/unit'
          commandOptions: '-var-file=./variables.tfvars'
